# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""


# Define the number of posts per page
paginate = 10


[permalinks]
blog = "/blog/:year/:month/:day/:filename/"


[taxonomies]
category = "categories"
tag = "tags"
author = "authors"


[markup]
[markup.goldmark.renderer]
unsafe = true