############################# English ############################
[en]
languageName = "En"
title = "Carmean Gohlke"
contentDir = "content/en" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."



############################# Chinese ############################
[zh]
languageName = "中文"
title = "Carmean Gohlke"
contentDir = "content/zh" # content/chinese
weight = 2
########### footer content ##########
footer_menu_left = "公司"
footer_menu_middle = "产品"
footer_menu_right = "支持"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
