# Main menu
[[main]]
name = "Home"
identifier = "menu.home"
url = "/"
weight = 1

[[main]]
name = "Our Services"
identifier = "menu.services"
url = "services"
weight = 2

[[main]]
name = "Research&Report"
identifier = "menu.research"
url = "research"
weight = 3

[[main]]
name = "Principal Insights"
identifier = "menu.principal"
url = "principal"
weight = 4

[[main]]
name = "About Us"
identifier = "menu.about"
url = "about"
weight = 5



# Top bar social links menu

[[topbar]]
weight = 2
name = "Facebook"
url = "http://facebook.com"
pre = "<i class='fab fa-2x fa-facebook'></i>"

[[topbar]]
weight = 3
name = "Twitter"
url = "http://twitter.com"
pre = "<i class='fab fa-2x fa-twitter'></i>"

[[topbar]]
weight = 4
name = "Email"
url = "mailto:hello@universal.com"
pre = "<i class='fas fa-2x fa-envelope'></i>"