# Main menu
[[main]]
name = "首页"
identifier = "menu.home"
url = "/"
weight = 1
[main.params]
type = ""


[[main]]
name = "我们的业务"
identifier = "menu.services"
url = "services"
weight = 2
[main.params]
type = "services"


[[main]]
name = "研究报告"
identifier = "menu.reports"
url = "reports"
weight = 3
[main.params]
type = "reports"


[[main]]
name = "校长洞见"
identifier = "menu.insights"
url = "insights"
weight = 4
[main.params]
type = "insights"


[[main]]
name = "关于我们"
identifier = "menu.about"
url = "about"
weight = 5
[main.params]
type = "about"



# Top bar social links menu

[[topbar]]
weight = 1
name = "Linkedin"
url = "http://linkedin.com"
pre = "<i class='fab fa-2x fa-linkedin'></i>"

[[topbar]]
weight = 2
name = "Wechat"
url = "http://wechat.com"
pre = "<i class='fab fa-2x fa-weixin'></i>"


# bottom
# bottom_middle
[[bottom_middle]]
name = "凯格咨询"
url = "/carmean-gohlke"
weight = 1

[[bottom_middle]]
name = "新闻活动"
url = "/events-activities"
weight = 2

[[bottom_middle]]
name = "联系我们"
url = "/contact"
weight = 3

[[bottom_middle]]
name = "加入我们"
url = "/about/join"
weight = 4


# bottom_right
[[bottom_right]]
name = "业务线"
url = "/business-lines"
weight = 1

[[bottom_right]]
name = "人才寻访"
url = "/talents-search"
weight = 2

[[bottom_right]]
name = "职业发展咨询"
url = "/career-development-consulting"
weight = 3

[[bottom_right]]
name = "薪酬福利咨询"
url = "/salary-and-welfare"
weight = 4