# Main menu
[[main]]
name = "首页"
identifier = "menu.home"
url = "/"
weight = 1

[[main]]
name = "服务"
identifier = "menu.services"
url = "/services"
weight = 2

[[main]]
name = "报告"
identifier = "menu.research"
url = "/research"
weight = 3

[[main]]
name = "Principal Insights"
identifier = "menu.principal"
url = "/principal"
weight = 4

[[main]]
name = "关于我们"
identifier = "menu.about"
url = "/about"
weight = 5



# Top bar social links menu

[[topbar]]
weight = 2
name = "Facebook"
url = "http://facebook.com"
pre = "<i class='fab fa-2x fa-facebook'></i>"

[[topbar]]
weight = 3
name = "Twitter"
url = "http://twitter.com"
pre = "<i class='fab fa-2x fa-twitter'></i>"

[[topbar]]
weight = 4
name = "Email"
url = "mailto:hello@universal.com"
pre = "<i class='fas fa-2x fa-envelope'></i>"



# bottom
# bottom_middle
[[bottom_middle]]
name = "Carmean&Gohlke"
url = "/carmean-gohlke"
weight = 1

[[bottom_middle]]
name = "Events&Activities"
url = "/events-activities"
weight = 2

[[bottom_middle]]
name = "Contact with us"
url = "/contact"
weight = 3

[[bottom_middle]]
name = "Join us"
url = "/join"
weight = 4


# bottom_right
[[bottom_right]]
name = "Business lines"
url = "/business-lines"
weight = 1

[[bottom_right]]
name = "Talents Search"
url = "/talents-search"
weight = 2

[[bottom_right]]
name = "Career Development Consulting"
url = "/career-development-consulting"
weight = 3

[[bottom_right]]
name = "Salary and Welfare"
url = "/salary-and-welfare"
weight = 4