# Main menu
[[main]]
name = "首页"
identifier = "menu.home"
url = "/"
weight = 1

[[main]]
name = "Features"
identifier = "menu.features"
url = "/img/template-easy-customize.png"
weight = 3

[[main]]
name = "Shortcodes"
identifier = "section.shortcodes"
url = ""
weight = 1
parent = "menu.features"
post = 1

[[main]]
name = "Header variations"
identifier = "section.headervariations"
url = ""
weight = 2
parent = "menu.features"
post = 2

[[main]]
name = "Accordions"
url = ""
weight = 1
parent = "section.shortcodes"

[[main]]
name = "Alerts"
url = ""
weight = 2
parent = "section.shortcodes"

[[main]]
name = "Buttons"
url = ""
weight = 3
parent = "section.shortcodes"

[[main]]
name = "Content Boxes"
url = ""
weight = 4
parent = "section.shortcodes"

[[main]]
name = "Horizontal Blocks"
url = ""
weight = 5
parent = "section.shortcodes"

[[main]]
name = "Pagination"
url = ""
weight = 6
parent = "section.shortcodes"

[[main]]
name = "Tabs"
url = ""
weight = 7
parent = "section.shortcodes"

[[main]]
name = "Typography"
url = ""
weight = 8
parent = "section.shortcodes"

[[main]]
name = "Default Sticky Header"
url = ""
weight = 1
parent = "section.headervariations"

[[main]]
name = "No Sticky Header"
url = ""
weight = 2
parent = "section.headervariations"

[[main]]
name = "Light Header"
url = ""
weight = 3
parent = "section.headervariations"

[[main]]
name = "Portfolio"
identifier = "menu.portfolio"
url = "/img/template-homepage.png"
weight = 3

[[main]]
name = "Portfolio"
identifier = "section.portfolio"
url = ""
weight = 1
parent = "menu.portfolio"
post = 1

[[main]]
name = "2 Columns"
url = ""
weight = 1
parent = "section.portfolio"

[[main]]
name = "2 Columns With Negative Space"
url = ""
weight = 2
parent = "section.portfolio"

[[main]]
name = "3 Columns"
url = ""
weight = 3
parent = "section.portfolio"

[[main]]
name = "3 Columns With Negative Space"
url = ""
weight = 4
parent = "section.portfolio"

[[main]]
name = "4 Columns"
url = ""
weight = 5
parent = "section.portfolio"

[[main]]
name = "4 Columns With Negative Space"
url = ""
weight = 6
parent = "section.portfolio"

[[main]]
name = "Portfolio - detail"
url = ""
weight = 7
parent = "section.portfolio"

[[main]]
name = "Portfolio - detail 2"
url = ""
weight = 8
parent = "section.portfolio"

[[main]]
name = "About"
identifier = "section.about"
url = ""
weight = 2
parent = "menu.portfolio"
post = 2

[[main]]
name = "About Us"
url = ""
weight = 1
parent = "section.about"

[[main]]
name = "Our Team"
url = ""
weight = 2
parent = "section.about"

[[main]]
name = "Marketing"
identifier = "section.marketing"
url = ""
weight = 3
parent = "menu.portfolio"
post = 2

[[main]]
name = "Packages"
url = ""
weight = 1
parent = "section.marketing"

[[main]]
name = "All Pages"
identifier = "menu.allpages"
url = ""
weight = 4

[[main]]
name = "Home"
identifier = "section.ap-home"
url = ""
weight = 1
parent = "menu.allpages"
post = 1

[[main]]
name = "About"
identifier = "section.ap-about"
url = ""
weight = 2
parent = "menu.allpages"
post = 1

[[main]]
name = "Marketing"
identifier = "section.ap-marketing"
url = ""
weight = 3
parent = "menu.allpages"
post = 1

[[main]]
name = "Portfolio"
identifier = "section.ap-portfolio"
url = ""
weight = 1
parent = "menu.allpages"
post = 2

[[main]]
name = "User Pages"
identifier = "section.ap-userpages"
url = ""
weight = 2
parent = "menu.allpages"
post = 2

[[main]]
name = "Shop"
identifier = "section.ap-shop"
url = ""
weight = 1
parent = "menu.allpages"
post = 3

[[main]]
name = "Shop - Order Process"
identifier = "section.ap-shoporderprocess"
url = ""
weight = 2
parent = "menu.allpages"
post = 3

[[main]]
name = "Contact"
identifier = "section.ap-contact"
url = ""
weight = 1
parent = "menu.allpages"
post = 4

[[main]]
name = "Pages"
identifier = "section.ap-pages"
url = ""
weight = 2
parent = "menu.allpages"
post = 4

[[main]]
name = "Blog"
identifier = "section.ap-blog"
url = "/blog/"
weight = 3
parent = "menu.allpages"
post = 4

[[main]]
name = "Blog Listing Big"
url = "/blog/"
weight = 1
parent = "section.ap-blog"

[[main]]
name = "Blog"
identifier = "menu.blog"
url = "/blog/"
weight = 5

[[main]]
name = "FAQ"
identifier = "menu.faq"
url = "/faq/"
weight = 6

[[main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 7


# Top bar social links menu

[[topbar]]
weight = 2
name = "Facebook"
url = "http://facebook.com"
pre = "<i class='fab fa-2x fa-facebook'></i>"

[[topbar]]
weight = 3
name = "Twitter"
url = "http://twitter.com"
pre = "<i class='fab fa-2x fa-twitter'></i>"

[[topbar]]
weight = 4
name = "Email"
url = "mailto:hello@universal.com"
pre = "<i class='fas fa-2x fa-envelope'></i>"