# Main menu
[[main]]
name = "首页"
identifier = "menu.home"
url = "/"
weight = 1

[[main]]
name = "我们的业务"
identifier = "menu.services"
url = "/services"
weight = 2

[[main]]
name = "研究报告"
identifier = "menu.reports"
url = "/reports"
weight = 3

[[main]]
name = "校长洞见"
identifier = "menu.insights"
url = "insights"
weight = 4

[[main]]
name = "关于我们"
identifier = "menu.about"
url = "/about"
weight = 5



# Top bar social links menu

[[topbar]]
weight = 2
name = "Facebook"
url = "http://facebook.com"
pre = "<i class='fab fa-2x fa-facebook'></i>"

[[topbar]]
weight = 3
name = "Twitter"
url = "http://twitter.com"
pre = "<i class='fab fa-2x fa-twitter'></i>"

[[topbar]]
weight = 4
name = "Email"
url = "mailto:hello@universal.com"
pre = "<i class='fas fa-2x fa-envelope'></i>"



# bottom
# bottom_middle
[[bottom_middle]]
name = "凯格咨询"
url = "/carmean-gohlke"
weight = 1

[[bottom_middle]]
name = "新闻活动"
url = "/events-activities"
weight = 2

[[bottom_middle]]
name = "联系我们"
url = "/contact"
weight = 3

[[bottom_middle]]
name = "加入我们"
url = "/join"
weight = 4


# bottom_right
[[bottom_right]]
name = "业务线"
url = "/business-lines"
weight = 1

[[bottom_right]]
name = "人才寻访"
url = "/talents-search"
weight = 2

[[bottom_right]]
name = "职业发展咨询"
url = "/career-development-consulting"
weight = 3

[[bottom_right]]
name = "薪酬福利咨询"
url = "/salary-and-welfare"
weight = 4