# Main menu
[[main]]
name = "Home"
identifier = "menu.home"
url = "/"
weight = 1
[main.params]
type = ""


[[main]]
name = "Our Services"
identifier = "menu.services"
url = "services"
weight = 2
[main.params]
type = "services"


[[main]]
name = "Research&Report"
identifier = "menu.reports"
url = "reports"
weight = 3
[main.params]
type = "reports"


[[main]]
name = "Principal Insights"
identifier = "menu.insights"
url = "insights"
weight = 4
[main.params]
type = "insights"


[[main]]
name = "About Us"
identifier = "menu.about"
url = "about"
weight = 5
[main.params]
type = "about"



# Top bar social links menu

[[topbar]]
weight = 1
name = "Linkedin"
url = "http://linkedin.com"
pre = "<i class='fab fa-2x fa-linkedin'></i>"

[[topbar]]
weight = 2
name = "Wechat"
url = "http://wechat.com"
pre = "<i class='fab fa-2x fa-weixin'></i>"


# bottom
# bottom_middle
[[bottom_middle]]
name = "Carmean&Gohlke"
url = "/carmean-gohlke"
weight = 1

[[bottom_middle]]
name = "Events&Activities"
url = "/news"
weight = 2

[[bottom_middle]]
name = "Contact with us"
url = "/contact"
weight = 3

[[bottom_middle]]
name = "Join us"
url = "/about/join"
weight = 4


# bottom_right
[[bottom_right]]
name = "Business lines"
url = "/business-lines"
weight = 1

[[bottom_right]]
name = "Talents Search"
url = "/talents-search"
weight = 2

[[bottom_right]]
name = "Career Development Consulting"
url = "/career-development-consulting"
weight = 3

[[bottom_right]]
name = "Salary and Welfare"
url = "/salary-and-welfare"
weight = 4